### ISSUE TITLE
Redeclaring queues and exchanges after each touch

### ISSUE THREAD

**Issue by dada-amater** [gameeapp/nette-rabbitmq#12]
Every time a producer/consumer touches any exchange/queue, it is redeclared in `QueueFactory` or `ExchangeFactory`. This is huge waste of performance and it killed our production RabbitMq server. We would like to switch off this behaviour in the config, like there is `autoSetupFabric: off` in Kdyby/RabbitMq extension.

**Comment by paveljanda** [comment]
@dada-amater What version do you use?

**Comment by dada-amater** [comment]
@paveljanda 
`gamee/nette-rabbitmq v2.0.0` via composer

**Comment by dada-amater** [comment]
Do you have any plans to resolve this issue?

**Comment by dada-amater** [comment]
I have forked this unmaintained repository. If you combe back, you can merge this:
https://github.com/dada-amater/nette-rabbitmq/commit/40f2f6d3ad76f44cd273af89d62e0e7a68eb5fac

**Comment by paveljanda** [comment]
@dada-amater This repository is maintained. :)

As I mentioned in PR #11 - please remove the composer.json alter and I will merge the PR immediately.

**Comment by dada-amater** [comment]
@paveljanda great, thanx
