### ISSUE TITLE
Possibility to stop consumer when error occurs…

### ISSUE THREAD

**Issue by her-ur** [gameeapp/nette-rabbitmq#20]
Hello, is there any possibility to stop consumer when error occurs? Typically when doctrine entity manager was closed I need to restart consumer job and supervisor starts it again.

If not can I send PR with new case branch here? https://github.com/gameeapp/nette-rabbitmq/blob/master/src/Consumer/Consumer.php#L79

Thank you for your answer.

**Comment by paveljanda** [comment]
Then there should exist supervisor job that will start your job again when you kill it ->
```php
$this->sentry->logMyError($e);
exit(1);
```

**Comment by her-ur** [comment]
But i need reject the message from the queue. If i call `exit(1)` supervisor start consumer again and broken message is requeued. Do you understand what i mean? There is an example:
```
public function consume(Message $message): int
{
        try {
            $this->callHandler();

        } catch (PersistentStorageException $e) {
            $this->logger->log($e, ILogger::ERROR);
           // here i need reject the message -> return IConsumer::MESSAGE_REJECT;
           // and kill consumer job
            exit(1);

        }

        return self::MESSAGE_ACK;
}
```

**Comment by paveljanda** [comment]
This is perfectly OK:

```php
try {
    $this->callHandler();

} catch (PersistentStorageException $e) {
	$this->logger->log($e, ILogger::ERROR);

	return IConsumer::MESSAGE_REJECT;

	exit(1);
}

return self::MESSAGE_ACK;
```

**Comment by her-ur** [comment]
Am I missing something? But `exit(1);` will never be executed because it's called after `return` statement.
IMHO `exit(1);` or `$client->stop();` must be called inside this method: https://github.com/gameeapp/nette-rabbitmq/blob/master/src/Consumer/Consumer.php#L79
Is that right?

**Comment by paveljanda** [comment]
When you call `return IConsumer::MESSAGE_REJECT;`, the message gets reject. Then you exit the code.

What does that mean: Your consumer gets restarted + the message gets rejected from your queue. Is that not what you want?

**Comment by her-ur** [comment]
> Your consumer gets restarted + the message gets rejected from your queue. Is that not what you want?

This is exactly what I want. But I don't know where exactly I have to call `exit(1);`? Because my handler is called within `Gamee\RabbitMQ\Consumer\Consumer::consume()` and only there message can be rejected. So I can only exit job or reject, but not both.

**Comment by paveljanda** [comment]
@her-ur Oh I see! Sorrry. :D

Maybe there you can implement some new signal that would reject the message and exit?

**Comment by her-ur** [comment]
>Maybe there you can implement some new signal that would reject the message and exit?

Exactly that I thought in first comment ;-) Happy that we understand each other now :-)
Do you know if is better to call `exit(1);` or `$client->stop();`?

**Comment by paveljanda** [comment]
Well this is a good question. Maybe I would use yours `$client->stop();` andwhen that works, it's good!

**Comment by her-ur** [comment]
Ok, thank you for your time! I'll send PR ;-)

**Comment by paveljanda** [comment]
Thank's for your patience. :)

**Comment by her-ur** [comment]
Here is PR: https://github.com/gameeapp/nette-rabbitmq/pull/21

**Comment by her-ur** [comment]
@paveljanda Hello :-) Could you have a look at https://github.com/gameeapp/nette-rabbitmq/pull/21 please? And merge it if it will be ok? Thank you very much!

**Comment by paveljanda** [comment]
Done. :)
